[server]
address = "127.0.0.1"
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#176b5b"
backgroundColor = "#f3f5f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#20272d"
font = "sans serif"
